#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

include: ["_pages"]
title: "V Congreso Iberoamericano de Investigación en Conservación del Patrimonio"
subtitle: "ICP 2024"
